### ISSUE TITLE
Feature request: support for sanitizing method arguments

### ISSUE THREAD

**Issue by fishtreesugar** [mimiquate/tower_bugsnag#22]
Thank you for the excellent library!

As mentioned in this comment https://github.com/bugsnag-elixir/bugsnag-elixir/issues/122#issuecomment-2394477122, it suggests using `tower_bugsnag` as a replacement for `bugsnag-elixir`. 

However, for our use case, there is still a missing feature compared to `bugsnag-elixir`: sanitization.
This feature is detailed in the `bugsnag-elixir` documentation here: https://hexdocs.pm/bugsnag/readme.html#sanitizer, which allows sanitizing method/function arguments. We handle a lot of Personally Identifiable Information (PII), such as names, dates of birth, addresses, and document IDs. Therefore, it's crucial to prevent any PII data from leaking to third-party vendors.

**Comment by grzuy** [comment]
Hi @fishtreesugar,

Thanks for the feedback and taking the time to report.

Supporting some sort of custom sanitization is a top priority.

**Comment by fishtreesugar** [comment]
I see. That doesn't align with my experience using `bugsnag-elixir`. Could you explain the reasoning behind handling the argument this way?

**Comment by grzuy** [comment]
> Yes, that makes sense. I also noticed that the handling of `plug.conn` is not expose same amount of information as [plugsnag](https://github.com/bugsnag-elixir/plugsnag/blob/master/lib/plugsnag/basic_error_report_builder.ex#L19-L29).
> 

Correct. Intentional.

> I completely agree with the conservative approach.

:+1: 
thanks for the feedback.
